CLIENT_NAME = TaxobClient
CLIENT_VERSION = 1.0
CLIENT_DIR = client/
CLIENT_FILES = *.c

SERVER_NAME = TaxobServer
SERVER_VERSION = 1.0
SERVER_DIR = server/
SERVER_FILES = *.c

COMMON_FILES = network/*.c

OUT_DIR = ./bin

all: directories $(CLIENT_NAME) $(SERVER_NAME)

directories:
	mkdir -p $(OUT_DIR)

$(CLIENT_NAME): $(CLIENT_DIR)$(CLIENT_FILES)
	gcc -o $(OUT_DIR)/$(CLIENT_NAME)-$(CLIENT_VERSION) $(COMMON_FILES) $(CLIENT_DIR)$(CLIENT_FILES)

$(SERVER_NAME): $(SERVER_DIR)$(SERVER_FILES)
	gcc -o $(OUT_DIR)/$(SERVER_NAME)-$(SERVER_VERSION) $(COMMON_FILES) $(SERVER_DIR)$(SERVER_FILES) 
